### PR TITLE
Main page

### PR DESCRIPTION
**Pull request by latifa-wakili**
this is an web page that created with html and css

### CODE REVIEW

**Comment by Orzala-2024** [comment]
Hi @latifa-wakili ,
you have done good works for this week project.  but consider below points before submission: 
-your files must not have any linters error.
-your HTML and CSS codes must pass freecodcamp Tribute page project test.
-give your page some styles.
-add some more descriptions in your pull request. 
-Try to make more commit messages.

**Comment by ahzamir** [comment]
@latifa-wakili 
- Although your partner provided you with a great review, You have to solve the linters issues so I can check your project code.

**Comment by latifa-wakili** [comment]
@ahzamir  Hi sir 
I solved all errors and changed some styles.
please check it and give new feedback.

**Review by ahzamir — APPROVED** [review]
### Hi @latifa-wakili 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

GreatJobThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Tribute Page project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
